### ISSUE TITLE
CERN: extract current user's auth in accept invite

### ISSUE THREAD

**Issue by LovisaLugnegard** [sciencemesh/accept-invite#8]
This is so we can call the protected endpoint /forward

**Comment by ishank011** [comment]
We need to call /ocm/invites/forward from the phoenix frontend, which is hosted on a different port than the ocmd service, so we'll have to send post request to the complete URL (http://localhost:19001/ocm/invites/forward for example) instead of just calling another JS method. So how do we extract the auth, specifically the current user's password to be passed onto the forward endpoint.

**Comment by labkode** [comment]
@ishank011 the phoenix setup uses OIDC and Reva is configured to use OIDC, so you don't need from Phoenix to extract any user information to call `/ocm/invite/forward`.

I need to look into the details of what you're doing there, but a priori, a simple a POST request to /ocm/invite/forward will be protected by default, and the code that deals with that in the gRPC part the user is already in the context. If is not the case, we are missing something.

**Comment by ishank011** [comment]
All calls made in phoenix are passed through the [requests.ocs](https://github.com/owncloud/owncloud-sdk/blob/2f6441b5f617564f590fa1c3e4f041849ef07ef2/src/helperFunctions.js#L523) method which sets the authorization headers. The issue with this is that it hardcodes the prefix of the URL, so one way to achive this is defining a generic request handler in the owncloud-sdk repo.

**Comment by LovisaLugnegard** [comment]
We can extract the user from the store, so if we don't want to define a generic req handler I guess we can user this user info for authentication to /forward. Let's discuss after stand-up.

**Comment by labkode** [comment]
1) create issue to Phoenix on how to extract user token
2) create issue to Phoenix to override options in the ownClod SDK (to call a different target URL that is not OCS).

**Comment by LovisaLugnegard** [comment]
Here's a link to the user store in Phoenix from where we can get the token: https://github.com/owncloud/phoenix/blob/master/src/store/user.js. I'll implement this and create a PR.
